### ISSUE TITLE
Star history stops working for my repo since May 8, 2023

### ISSUE THREAD

**Issue by zaikunzhang** [star-history/star-history#317]
Hello,

Thank you very much for this wonderful tool! 

For my repo at https://github.com/libprima/prima , I added the following line in the [README](https://github.com/libprima/prima/edit/main/README.md) file (copied from https://star-history.com/#libprima/prima&Date ):

```
[![Star History Chart](https://api.star-history.com/svg?repos=libprima/prima&type=Date)](https://star-history.com/#libprima/prima&Date)
```

Everything has been working great until yesterday (8 May 2023). However, it stopped working since then. The figure disappears and a broken link is shown. Did I do something wrong? 

FYI, the figure still shows in the Apple app of GitHub, but now in web browsers. 

It would be great if you could take a look. 

Many thanks,
Zaikun

**Comment by d-bytebase** [comment]
Hey @zaikunzhang , is this issue consistent? The chart works for me.

**Comment by zaikunzhang** [comment]
Hi @d-bytebase . Thank you for your prompt response!

Yes, it is consistent on my side for my repo https://github.com/libprima/prima . I tried various devices and various browsers. It does not work except for the Apple App of GitHub. 

Thanks.

**Comment by zaikunzhang** [comment]
Update: This seems to be due to the length of my README --- star history stops working if it is embedded at the bottom of a lengthy README. Compare

https://github.com/libprima/prima 
https://github.com/zaikunzhang/zaikunzhang

Thank you for taking a look.

Best regards,
Zaikun

**Comment by d-bytebase** [comment]
I'm gald you figured it out. Thanks for letting us know.

**Comment by zaikunzhang** [comment]
Hi @d-bytebase ! Thank you for responding. 

However, I don't think the problem is solved. It does not work if the README is long enough. This seems to be a bug. It would be nice if you could take a look.

**Comment by d-bytebase** [comment]
Sure, let me take a look, but it might be a bug with GitHub itself.

When I move the star-history to the top of the content, the picture will show. It's not just the length of the readme file.

**Comment by d-bytebase** [comment]
I found a work-around to use img below, but it cannot link to the page.

```
<img src="https://api.star-history.com/svg?repos=libprima/prima&type=Date">
```

**Comment by zaikunzhang** [comment]
Thank you very much @d-bytebase . I will take this work-around for the moment.
