### ISSUE TITLE
Sometimes it show error: "Unauthorized: Access Token Unauthorized" or "Forbidden: GitHub API rate limit exceeded"

### ISSUE THREAD

**Issue by xumeng** [star-history/star-history#329]
Sometimes it show error: 
"Unauthorized: Access Token Unauthorized" 
or 
"Forbidden: GitHub API rate limit exceeded"

**Comment by tianzhou** [comment]
Please supply your own access token (it's only stored in your local browser)

![CleanShot 2023-10-03 at 00-11-07 png](https://github.com/star-history/star-history/assets/230323/10f09808-d8e4-4792-bb12-d68c223930eb)
