### ISSUE TITLE
Starlet #8 doesn't load

### ISSUE THREAD

**Issue by adamlui** [star-history/star-history#371]
For https://star-history.com/blog/Prompt-flow I tried in Firefox & Chrome, an endless spinner appears

https://github.com/star-history/star-history/assets/10906554/d28cac60-ae33-403a-bb91-921647b22470

**Comment by tianzhou** [comment]
Fix in https://github.com/star-history/star-history/commit/aa45811356bc445e766b8ea18e365c21ea861f59

Should be https://star-history.com/blog/prompt-flow instead of https://star-history.com/blog/Prompt-flow
