### ISSUE TITLE
'Invalid date' shown in bylines of Starlet issues #11 onward

### ISSUE THREAD

**Issue by adamlui** [star-history/star-history#372]
![image](https://github.com/star-history/star-history/assets/10906554/910efaf7-2cf6-44fc-a396-6eea61a76ac6)
![image](https://github.com/star-history/star-history/assets/10906554/d863f426-77e8-4f5d-a7be-012e4c61ecf8)
![image](https://github.com/star-history/star-history/assets/10906554/7a17085b-e77e-45b2-8ec3-cf3b6fb4ddab)
![image](https://github.com/star-history/star-history/assets/10906554/d4382ed0-c60e-46fc-af1f-ce8b4036e187)

**Comment by tianzhou** [comment]
Did a restructure. Should be fine now.
