### ISSUE TITLE
Negative star count at project start

### ISSUE THREAD

**Issue by fsimonis** [star-history/star-history#391]
The start count for the beginning of the repo `precice/precice` is -30. Are you extrapolating by any chance? 0 stars should be a decent assumption for the time of creation. 

[![Star History Chart](https://api.star-history.com/svg?repos=precice/precice&type=Date)](https://star-history.com/#precice/precice)

**Comment by tianzhou** [comment]
We do extrapolate, seems like a bug.

**Comment by peasoft** [comment]
Same problem.
