### ISSUE TITLE
Add repo-analytics, also from tim qian

### ISSUE THREAD

**Issue by Botspot** [star-history/star-history#396]
Star-history and repo-analytics were both projects by github user @timqian.
https://repo-analytics.github.io/
![image](https://github.com/star-history/star-history/assets/54716352/830e159c-6455-48f7-b1ad-1a0727dd286f)

He seems to no longer be very active in these projects, so presumably that is why ByteBase has taken over Star History.
This is a request to ByteBase to fix up and take over the Repo Analytics project too. Right now it is completely broken and unusable, and as a result I no longer have any idea how many clones my project has received over its lifetime. :(

Hopefully someboey who sees this will know @timqian personally to copy this data over to a new domain name? I have tried contacting him myself without ever receiving back a response.

**Comment by tianzhou** [comment]
This is not the place to contact. Sorry

**Comment by Botspot** [comment]
Please suggest a better place to contact.

**Comment by Botspot** [comment]
@tianzhou, is there a better place to contact? Please advise.
