### ISSUE TITLE
Rate limit exceeded in Firefox (but not in Chrome)

### ISSUE THREAD

**Issue by JesseAldridge** [star-history/star-history#439]
I'm using the same token on both.
It works in Chrome, but I get rate limited exceeded in Firefox.

**Comment by tianzhou** [comment]
Rate limit is handled in the background, Firefox and Chrome are no different. Likely a timing issue.

**Comment by JesseAldridge** [comment]
A timing issue?
I've run into this a few different times across several days.
It consistently works in Chrome and consistently does not work in Firefox.
